### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by mrpavlikov** [livingstyleguide/livingstyleguide#104]
Here's what I'm getting on Ubuntu 14.04

```
$ livingstyleguide compile src/styles/styleguide.lsg www/styleguide.html
/usr/lib/ruby/vendor_ruby/sass/script/literal.rb:7:in `<module:Script>': superclass mismatch for class Literal (TypeError)
	from /usr/lib/ruby/vendor_ruby/sass/script/literal.rb:1:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches/browser_support.rb:2:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches.rb:1:in `each'
	from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/vendor_ruby/compass/sass_extensions.rb:9:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/vendor_ruby/compass.rb:5:in `block in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/compass.rb:4:in `each'
	from /usr/lib/ruby/vendor_ruby/compass.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/livingstyleguide-1.2.1/lib/livingstyleguide.rb:5:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/livingstyleguide-1.2.1/bin/livingstyleguide:3:in `<top (required)>'
	from /usr/local/bin/livingstyleguide:23:in `load'
	from /usr/local/bin/livingstyleguide:23:in `<main>'
```

Gems installed:

```
$ gem list

*** LOCAL GEMS ***

ast (2.0.0)
astrolabe (1.3.0)
breakpoint (2.5.0)
bundler (1.7.9, 1.7.8, 1.7.7, 1.7.6, 1.7.4, 1.7.3, 1.7.2)
chunky_png (1.3.3, 1.3.2, 1.3.1, 1.2.8)
compass (1.0.1, 0.12.2)
compass-core (1.0.1, 1.0.0.rc.1, 1.0.0.alpha.20)
compass-import-once (1.0.5, 1.0.4)
diff-lcs (1.2.5)
ffi (1.9.6, 1.9.5, 1.9.3)
foundation (1.0.4)
fssm (0.2.10)
hooks (0.4.0, 0.3.3)
json (1.8.1)
livingstyleguide (1.2.1)
mini_portile (0.6.1)
minisyntax (0.2.3)
multi_json (1.10.1)
nokogiri (1.6.5, 1.6.4.1, 1.6.4)
oily_png (1.1.2, 1.1.1, 1.1.0)
powerpack (0.0.9)
rainbow (2.0.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.5, 0.9.2)
rdoc (4.2.0, 4.1.2, 4.1.1, 3.9.4)
redcarpet (3.2.2, 3.0.0)
rspec (3.1.0)
rspec-core (3.1.7)
rspec-expectations (3.1.2)
rspec-mocks (3.1.3)
rspec-support (3.1.2)
ruby-progressbar (1.7.1, 1.7.0)
sass (3.4.9, 3.2.12)
sassy-maps (0.4.0)
scss-lint (0.31.0)
susy (2.1.3)
thor (0.19.1)
tilt (2.0.1)
uber (0.0.12)
```

```
$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

What could it be?

**Comment by hagenburger** [comment]
I plan to release version 2.0.0 soon. This contains a major rewrite in many parts of the Gem. I hope this get solved. I let you know as soon as I think this could be tested on a pre version.

**Comment by hagenburger** [comment]
As this is quite old I’m closing this for now. If it’s still an issue, please reopen. Thanks!
