### ISSUE TITLE
Run website (beginner needs help)

### ISSUE THREAD

**Issue by benevbright** [livingstyleguide/livingstyleguide#229]
Hi, 
I'm very new on Ruby and Rails.

I'm trying to run the `/website` in this repo to know LSG. 
But when I try to run `middleman`,

The error message is shown on the browser saying 
```
Sass::Syntax error:File to import not found or unreadable: livingstyleguide
...
.../component/_markdown.scss:52
```

And on the terminal,
```
website (js) $ middleman
WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 1.3.3, ~> 1.3)
      tzinfo (~> 1.1)
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.== The Middleman is loading
Thread.exclusive is deprecated, use Mutex/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:21:in
`logger'/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:45:in
`block (2 levels) in start_threaded_reactor'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:44:in
`block in start_threaded_reactor'
== LiveReload is waiting for a browser to connect
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/_
_middleman"
Thread.exclusive is deprecated, use Mutex
/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:21:in`logger'
/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:51:in`block (4 levels) in start_threaded_reactor'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:24:in `trigger_on_open'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:114:in `block in dispatch'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/em/deferrable.rb:151:in `set_deferred_status'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/em/deferrable.rb:191:in `succeed'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/handshake.rb:150:in `process'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/handshake.rb:29:in `receive_data'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:127:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:78:in `receive_data'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:44:in`block in start_threaded_reactor'
Thread.exclusive is deprecated, use Mutex
/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:21:in`logger'
/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:59:in`block (4 levels) in start_threaded_reactor'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:18:in `trigger_on_message'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/message_processor_06.rb:52:in `message'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/framing07.rb:118:in `process_data'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/handler.rb:47:in `receive_data'
/Library/Ruby/Gems/2.3.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:76:in `receive_data'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/Library/Ruby/Gems/2.3.0/gems/middleman-livereload-3.1.1/lib/middleman-livereload/reactor.rb:44:in`block in start_threaded_reactor'
```

Is this version issue?
Any suggestion will help me. Thanks.

**Comment by hagenburger** [comment]
Quick suggestion before looking into details: Have you tried using [Bundler](https://bundler.io)?

``` sh
bundle                  # Install dependencies for the project
cd website
bundle                  # Install dependencies for the website
bundle exec middleman   # run website
```

**Comment by benevbright** [comment]
Hi, Thanks for response. 

Yes, I used `bundler` to install gems. 
but I did it on the `/website' folder.
And I used `middleman` to run the website.

I tried to execute like `bundle exec middleman` instead of just `middleman`.
Bur result is same.

**Comment by benevbright** [comment]
OK, I've mistaken. 
I was on the 'js' branch. and when I execute `bundle` on the root folder, there was error on the line 3: 'gemspec' for some reason. 
I checkout to master branch and execute `bundle` on the root folder and execute `middleman` on the /website folder and it works. 

Thanks.
