### ISSUE TITLE
2.1.0 breaks when you don't have sassc-rails installed

### ISSUE THREAD

**Issue by rmehner** [livingstyleguide/livingstyleguide#233]
Hey there :wave:

#232 made the change from sass to sassc, however it also adds an implicit dependency to sassc-rails here: https://github.com/livingstyleguide/livingstyleguide/blob/fc9564f2c0c7ee93c9b0925c3715bbb3beb79cfc/lib/livingstyleguide/integration/rails.rb#L9

If you update from 2.0.3 to 2.1.0 and don't have sassc-rails installed, your app will break with:

```
NameError:
  uninitialized constant SassC::Rails
```

Since sassc-rails doesn't work out of the box for one of the apps I'm working on, I'll downgrade LSG to 2.0.3 for now until I have time to investigate further :)

Have a great day all around!

**Comment by droznyk** [comment]
I have the same problem in my project.
```
/home/patryk/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant': uninitialized constant SassC::Rails (NameError)
	from /home/patryk/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	from /home/patryk/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	from /home/patryk/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/livingstyleguide-2.1.0/lib/livingstyleguide/integration/rails.rb:9:in `block in <class:LivingStyleGuideRailtie>'
```
Downgrade to `2.0.3` worked for me.
